on:
  workflow_dispatch:
    inputs:
      graalpy_version:
        type: string
        required: true
      package:
        type: string
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Containerized Build
        uses: ./.github/actions/manylinux-action
        with:
          graalpy_version: ${{ inputs.graalpy_version }}
          package: ${{ inputs.package }}

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: workspace_artifacts
          path: ${{ github.workspace }}
